FROM ar-node:4

RUN mkdir -p /usr/src/app/reveal-frontend && mkdir -p /usr/src/app/express-server

COPY ./web /usr/src/app/reveal-frontend
COPY ./express-server /usr/src/app/express-server

RUN cd /usr/src/app/reveal-frontend && yarn build test
#RUN cd /usr/src/app/express-server && yarn build test

EXPOSE 3000

WORKDIR /usr/src/app